2025-07-16 11:05:08,888 [INFO] Start polling
2025-07-16 11:05:09,330 [INFO] Run polling for bot @gfp_giftincase_bot id=7970077758 - 'GFP GiftInCase'
2025-07-16 11:05:19,175 [INFO] Message sent to user_id 7727904991
2025-07-16 11:05:29,089 [INFO] Message sent to user_id 7727904991
2025-07-16 11:05:32,680 [INFO] Message sent to user_id 7727904991
2025-07-16 11:10:35,197 [INFO] Polling stopped for bot @gfp_giftincase_bot id=7970077758 - 'GFP GiftInCase'
2025-07-16 11:10:35,197 [INFO] Polling stopped
2025-07-16 11:10:35,532 [ERROR] Task exception was never retrieved
future: <Task finished name='Task-2' coro=<Server.serve() done, defined at D:\PROJECTS\Python\Freelance\TGАuthenticator\venv\lib\site-packages\uvicorn\server.py:69> exception=KeyboardInterrupt()>
Traceback (most recent call last):
  File "D:\PROJECTS\Python\Freelance\TGАuthenticator\main.py", line 97, in <module>
    "status": "success",
  File "C:\Users\fgrgi\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\fgrgi\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\fgrgi\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\fgrgi\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\fgrgi\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\fgrgi\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\PROJECTS\Python\Freelance\TGАuthenticator\venv\lib\site-packages\uvicorn\server.py", line 70, in serve
    with self.capture_signals():
  File "C:\Users\fgrgi\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 142, in __exit__
    next(self.gen)
  File "D:\PROJECTS\Python\Freelance\TGАuthenticator\venv\lib\site-packages\uvicorn\server.py", line 331, in capture_signals
    signal.raise_signal(captured_signal)
KeyboardInterrupt
2025-07-16 11:10:39,808 [INFO] Start polling
2025-07-16 11:10:40,214 [INFO] Run polling for bot @gfp_giftincase_bot id=7970077758 - 'GFP GiftInCase'
2025-07-16 11:10:43,657 [INFO] Message sent to user_id 7727904991
